import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const build = Bun.spawn(['cargo', 'build', '--manifest-path', `${root}wasm/Cargo.toml`,
  '--locked', '--offline', '--release', '--target', 'wasm32-unknown-unknown'], {
  stdout: 'inherit', stderr: 'inherit', env: { ...process.env, CARGO_TARGET_DIR: `${root}wasm/target` },
})
if (await build.exited !== 0) process.exit(1)
const bytes = await readFile(`${root}wasm/target/wasm32-unknown-unknown/release/gum_video.wasm`)
const module = new WebAssembly.Module(bytes)
if (WebAssembly.Module.imports(module).length) throw new Error('Video WASM must have no host imports')
await mkdir(`${root}src/generated`, { recursive: true })
await writeFile(`${root}src/generated/wasm.ts`,
  '// Generated by bun run build:wasm. See wasm/vendor/README.md and THIRD_PARTY_NOTICES.md.\n'
  + `export const wasm_base64: string = '${bytes.toString('base64')}'\n`)
await writeFile(`${root}THIRD_PARTY_NOTICES.md`,
  '# Third-party notices\n\nThe bundled WASM links minih264 (CC0-1.0), pinned at\n'
  + '`b0baea7a80ef9d12da97301dd1099b8791b5ba43`.\n'
  + 'Source: https://github.com/lieff/minih264\n\n'
  + '## minih264 license\n\n```text\n'
  + (await readFile(`${root}wasm/vendor/LICENSE.minih264`, 'utf8')).trim() + '\n```\n')
console.log(`Video WASM: ${bytes.length.toLocaleString()} bytes; no host imports`)
